### ISSUE TITLE
Mystery shift error

### ISSUE THREAD

**Issue by jakebeal** [SD2E/sbol-dictionary-maintainer#22] opened 2019-05-21 14:09 UTC
In the reagent sheet, there's an error that I can't figure out how to resolve:
> SD2 Dictionary (1.4.2) Updated 2019-05-21 13:58:43: Dictionary update failed: Found potential shift in column "EmeraldCloud UID" of tab "Reagent"

**Comment by mwes** [comment] 2019-05-22 13:56
FYI, this appears to be causing minor issues resolving against CalTech's iptg and atc reagents when we query for them. They're present in the dictionary sheet, but can't be resolved when queried against (presumably because they not being synced to SBH). We can work around this for now.

**Comment by dsumorok-raytheon** [comment] 2019-05-22 14:24
This appears to be caused by a bug in the Dictionary program.

**Comment by jakebeal** [comment] 2019-05-22 16:42
Should be resolved by #24, to be deployed shortly.

**Closed as completed** 2019-05-22 21:19 UTC
Labels: bug
